import { StyleProp, TextStyle } from 'react-native'

export const mb-35: StyleProp<TextStyle>
export const mt-15: StyleProp<TextStyle>
export const accordion: StyleProp<TextStyle>
export const card: StyleProp<TextStyle>
export const active: StyleProp<TextStyle>
export const card-header: StyleProp<TextStyle>
export const btn: StyleProp<TextStyle>
export const not-collapsed: StyleProp<TextStyle>
export const card-body: StyleProp<TextStyle>
export const no-scroll: StyleProp<TextStyle>
export const contentBox: StyleProp<TextStyle>
export const title: StyleProp<TextStyle>
export const subTitle: StyleProp<TextStyle>
export const hide-on-lg: StyleProp<TextStyle>
export const show-on-lg: StyleProp<TextStyle>
export const hide-on-md: StyleProp<TextStyle>
export const show-on-md: StyleProp<TextStyle>
export const list-inline: StyleProp<TextStyle>
export const modal-backdrop: StyleProp<TextStyle>
export const modal: StyleProp<TextStyle>
export const modal-dialog-centered: StyleProp<TextStyle>
export const modal-dialog: StyleProp<TextStyle>
export const modal-content: StyleProp<TextStyle>
export const modal-header: StyleProp<TextStyle>
export const close: StyleProp<TextStyle>
export const modal-body: StyleProp<TextStyle>
export const form-group: StyleProp<TextStyle>
export const form-control: StyleProp<TextStyle>
export const checkbox: StyleProp<TextStyle>
export const radio: StyleProp<TextStyle>
export const default: StyleProp<TextStyle>
export const legal: StyleProp<TextStyle>
export const inline-buttons: StyleProp<TextStyle>
export const modal-footer: StyleProp<TextStyle>
export const modal-xl: StyleProp<TextStyle>
export const swiper-container: StyleProp<TextStyle>
export const v-dropdown-item[data-v-138dff1d]: StyleProp<TextStyle>
export const default-option): StyleProp<TextStyle>
export const selected: StyleProp<TextStyle>
export const v-dropdown-container[data-v-138dff1d]: StyleProp<TextStyle>
export const b-form-btn-label-controlform-control>label: StyleProp<TextStyle>
export const __vuescroll: StyleProp<TextStyle>
export const __rail-is-vertical: StyleProp<TextStyle>
export const __bar-is-vertical: StyleProp<TextStyle>
export const v-select: StyleProp<TextStyle>
export const vs__dropdown-toggle: StyleProp<TextStyle>
export const vs__selected: StyleProp<TextStyle>
export const vs__dropdown-option: StyleProp<TextStyle>
export const vs__dropdown-option--highlight: StyleProp<TextStyle>
export const vs__actions: StyleProp<TextStyle>
export const vs__open-indicator: StyleProp<TextStyle>
export const arrow-down: StyleProp<TextStyle>
export const v-dropdown-container: StyleProp<TextStyle>
export const v-select-toggle: StyleProp<TextStyle>
export const vs__search: StyleProp<TextStyle>
export const vs__clear: StyleProp<TextStyle>
export const vs__dropdown-menu: StyleProp<TextStyle>
export const contentWrapper: StyleProp<TextStyle>
export const container: StyleProp<TextStyle>
