query ($page: Int, $locations: String, $categories: String) {
	offers(page: $page, locations: $locations, categories: $categories) {
		id
		name
		image
		type
		description
		expirationDate
		requirements
	}
}
